// Simple script to generate and insert sample products
const sampleProducts = [
  // PlayStation Games (10 products)
  {
    title: 'لعبة Spider-Man 2',
    title_en: 'Spider-Man 2',
    description: 'مغامرة بطولية في مدينة نيويورك مع الرجل العنكبوت في أحدث إصدارات بلايستيشن',
    description_en: 'Heroic adventure in New York City with Spider-Man in the latest PlayStation release',
    price: 299,
    original_price: 399,
    category: 'playstation',
    subcategory: 'PS5',
    sku: 'MT0001',
    stock: 999,
    is_new: true,
    is_limited: false,
    status: 'active',
    tags: ['action', 'adventure', 'exclusive', 'sony', 'ps5'],
    images: ['https://picsum.photos/400/600?random=1', 'https://picsum.photos/400/600?random=2'],
    image: 'https://picsum.photos/400/600?random=1',
    is_digital: true,
    compatibility: 'PlayStation 5'
  },
  {
    title: 'لعبة God of War Ragnarok',
    title_en: 'God of War Ragnarok',
    description: 'ملحمة نورسية مذهلة مع كرياتوس وأتريوس في عالم الآلهة الاسكندنافية',
    description_en: 'Epic Norse saga with Kratos and Atreus in the world of Scandinavian gods',
    price: 279,
    original_price: 349,
    category: 'playstation',
    subcategory: 'PS5',
    sku: 'MT0002',
    stock: 999,
    is_new: false,
    is_limited: true,
    status: 'active',
    tags: ['action', 'adventure', 'mythology', 'sony', 'ps5'],
    images: ['https://picsum.photos/400/600?random=3'],
    image: 'https://picsum.photos/400/600?random=3',
    is_digital: true,
    compatibility: 'PlayStation 4, PlayStation 5'
  },
  {
    title: 'لعبة The Last of Us Part II',
    title_en: 'The Last of Us Part II',
    description: 'قصة نهاية العالم المؤثرة في عالم ما بعد الكارثة مع إيلي وجويل',
    description_en: 'Touching post-apocalyptic story in a devastated world with Ellie and Joel',
    price: 199,
    original_price: 299,
    category: 'playstation',
    subcategory: 'PS4',
    sku: 'MT0003',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['action', 'adventure', 'story', 'sony', 'ps4'],
    images: ['https://picsum.photos/400/600?random=4'],
    image: 'https://picsum.photos/400/600?random=4',
    is_digital: true,
    compatibility: 'PlayStation 4'
  },
  {
    title: 'لعبة Horizon Forbidden West',
    title_en: 'Horizon Forbidden West',
    description: 'استكشف عالم ما بعد الكارثة في مغامرة مذهلة مليئة بالآلات والأسرار',
    description_en: 'Explore a post-apocalyptic world in a stunning adventure full of machines and secrets',
    price: 259,
    category: 'playstation',
    subcategory: 'PS5',
    sku: 'MT0004',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['action', 'adventure', 'open-world', 'sony', 'ps5'],
    images: ['https://picsum.photos/400/600?random=5'],
    image: 'https://picsum.photos/400/600?random=5',
    is_digital: true,
    compatibility: 'PlayStation 4, PlayStation 5'
  },
  {
    title: 'لعبة Gran Turismo 7',
    title_en: 'Gran Turismo 7',
    description: 'تجربة سباقات واقعية مع أكثر من 400 سيارة في بيئات متنوعة',
    description_en: 'Realistic racing experience with over 400 cars in diverse environments',
    price: 289,
    category: 'playstation',
    subcategory: 'PS5',
    sku: 'MT0005',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['racing', 'simulation', 'cars', 'sony', 'ps5'],
    images: ['https://picsum.photos/400/600?random=6'],
    image: 'https://picsum.photos/400/600?random=6',
    is_digital: true,
    compatibility: 'PlayStation 4, PlayStation 5'
  },
  {
    title: 'لعبة Ratchet & Clank',
    title_en: 'Ratchet & Clank: Rift Apart',
    description: 'مغامرة فضائية مرحة مع راتشيت وكلانك في عالم مليء بالمفاجآت',
    description_en: 'Fun space adventure with Ratchet and Clank in a world full of surprises',
    price: 249,
    category: 'playstation',
    subcategory: 'PS5',
    sku: 'MT0006',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['platform', 'adventure', 'fun', 'sony', 'ps5'],
    images: ['https://picsum.photos/400/600?random=7'],
    image: 'https://picsum.photos/400/600?random=7',
    is_digital: true,
    compatibility: 'PlayStation 5'
  },
  {
    title: 'لعبة Ghost of Tsushima',
    title_en: 'Ghost of Tsushima',
    description: 'رحلة ساموراي في اليابان الإقطاعية مع قتال سيوف مذهل',
    description_en: 'Samurai journey in feudal Japan with amazing sword combat',
    price: 229,
    original_price: 299,
    category: 'playstation',
    subcategory: 'PS4',
    sku: 'MT0007',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['action', 'adventure', 'samurai', 'sony', 'ps4'],
    images: ['https://picsum.photos/400/600?random=8'],
    image: 'https://picsum.photos/400/600?random=8',
    is_digital: true,
    compatibility: 'PlayStation 4'
  },
  {
    title: 'لعبة Death Stranding',
    title_en: 'Death Stranding',
    description: 'مغامرة توصيل في عالم محطم مليء بالألغاز والمخاطر',
    description_en: 'Delivery adventure in a broken world full of puzzles and dangers',
    price: 189,
    category: 'playstation',
    subcategory: 'PS4',
    sku: 'MT0008',
    stock: 999,
    is_new: false,
    is_limited: true,
    status: 'active',
    tags: ['adventure', 'puzzle', 'unique', 'sony', 'ps4'],
    images: ['https://picsum.photos/400/600?random=9'],
    image: 'https://picsum.photos/400/600?random=9',
    is_digital: true,
    compatibility: 'PlayStation 4'
  },
  {
    title: 'لعبة Bloodborne',
    title_en: 'Bloodborne',
    description: 'لعبة أكشن RPG في عالم قوطي مليء بالوحوش والأسرار',
    description_en: 'Action RPG game in a gothic world full of monsters and secrets',
    price: 179,
    category: 'playstation',
    subcategory: 'PS4',
    sku: 'MT0009',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['rpg', 'action', 'gothic', 'sony', 'ps4'],
    images: ['https://picsum.photos/400/600?random=10'],
    image: 'https://picsum.photos/400/600?random=10',
    is_digital: true,
    compatibility: 'PlayStation 4'
  },
  {
    title: 'لعبة Uncharted: Legacy of Thieves',
    title_en: 'Uncharted: Legacy of Thieves Collection',
    description: 'مجموعة أفضل مغامرات ناثان دريك في جولة حول العالم',
    description_en: 'Collection of Nathan Drake\'s best adventures around the world',
    price: 199,
    category: 'playstation',
    subcategory: 'PS5',
    sku: 'MT0010',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['adventure', 'action', 'collection', 'sony', 'ps5'],
    images: ['https://picsum.photos/400/600?random=11'],
    image: 'https://picsum.photos/400/600?random=11',
    is_digital: true,
    compatibility: 'PlayStation 5'
  },

  // Xbox Games (10 products)
  {
    title: 'لعبة Halo Infinite',
    title_en: 'Halo Infinite',
    description: 'عودة ماستر شيف في أحدث إصدارات هالو مع معارك فضائية مذهلة',
    description_en: 'Master Chief returns in the latest Halo with amazing space battles',
    price: 299,
    category: 'xbox',
    subcategory: 'Xbox Series X',
    sku: 'MT0011',
    stock: 999,
    is_new: true,
    is_limited: false,
    status: 'active',
    tags: ['action', 'shooter', 'sci-fi', 'microsoft', 'xbox'],
    images: ['https://picsum.photos/400/600?random=12'],
    image: 'https://picsum.photos/400/600?random=12',
    is_digital: true,
    compatibility: 'Xbox One, Xbox Series X/S'
  },
  {
    title: 'لعبة Forza Horizon 5',
    title_en: 'Forza Horizon 5',
    description: 'سباقات مفتوحة العالم في المكسيك مع أكثر من 500 سيارة',
    description_en: 'Open-world racing in Mexico with over 500 cars',
    price: 279,
    category: 'xbox',
    subcategory: 'Xbox Series X',
    sku: 'MT0012',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['racing', 'open-world', 'cars', 'microsoft', 'xbox'],
    images: ['https://picsum.photos/400/600?random=13'],
    image: 'https://picsum.photos/400/600?random=13',
    is_digital: true,
    compatibility: 'Xbox One, Xbox Series X/S'
  },
  {
    title: 'لعبة Gears 5',
    title_en: 'Gears 5',
    description: 'إطلاق نار تعاوني في عالم ما بعد الكارثة مع فريق دلتا',
    description_en: 'Cooperative shooting in a post-apocalyptic world with Delta Squad',
    price: 199,
    original_price: 249,
    category: 'xbox',
    subcategory: 'Xbox One',
    sku: 'MT0013',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['shooter', 'action', 'co-op', 'microsoft', 'xbox'],
    images: ['https://picsum.photos/400/600?random=14'],
    image: 'https://picsum.photos/400/600?random=14',
    is_digital: true,
    compatibility: 'Xbox One, Xbox Series X/S'
  },
  {
    title: 'لعبة Sea of Thieves',
    title_en: 'Sea of Thieves',
    description: 'مغامرة بحرية مع الأصدقاء في بحر مليء بالكنوز والمخاطر',
    description_en: 'Pirate adventure with friends in a sea full of treasures and dangers',
    price: 159,
    category: 'xbox',
    subcategory: 'Game Pass',
    sku: 'MT0014',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['adventure', 'pirates', 'multiplayer', 'microsoft', 'xbox'],
    images: ['https://picsum.photos/400/600?random=15'],
    image: 'https://picsum.photos/400/600?random=15',
    is_digital: true,
    compatibility: 'Xbox One, Xbox Series X/S'
  },
  {
    title: 'لعبة Microsoft Flight Simulator',
    title_en: 'Microsoft Flight Simulator',
    description: 'محاكي طيران واقعي يغطي كامل كوكب الأرض',
    description_en: 'Realistic flight simulator covering the entire planet Earth',
    price: 349,
    category: 'xbox',
    subcategory: 'Xbox Series X',
    sku: 'MT0015',
    stock: 999,
    is_new: false,
    is_limited: true,
    status: 'active',
    tags: ['simulation', 'flight', 'realistic', 'microsoft', 'xbox'],
    images: ['https://picsum.photos/400/600?random=16'],
    image: 'https://picsum.photos/400/600?random=16',
    is_digital: true,
    compatibility: 'Xbox Series X/S, PC'
  },
  {
    title: 'لعبة Ori and the Will of the Wisps',
    title_en: 'Ori and the Will of the Wisps',
    description: 'منصة فنية مذهلة مع أوري في عالم سحري مليء بالألغاز',
    description_en: 'Artistic platformer with Ori in a magical world full of puzzles',
    price: 149,
    category: 'xbox',
    subcategory: 'Xbox One',
    sku: 'MT0016',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['platform', 'artistic', 'puzzle', 'microsoft', 'xbox'],
    images: ['https://picsum.photos/400/600?random=17'],
    image: 'https://picsum.photos/400/600?random=17',
    is_digital: true,
    compatibility: 'Xbox One, Xbox Series X/S, PC'
  },
  {
    title: 'لعبة Cuphead',
    title_en: 'Cuphead',
    description: 'لعبة إطلاق نار كلاسيكية برسم يدوي في عالم كرتوني',
    description_en: 'Classic hand-drawn shooting game in a cartoon world',
    price: 129,
    category: 'xbox',
    subcategory: 'Xbox One',
    sku: 'MT0017',
    stock: 999,
    is_new: false,
    is_limited: true,
    status: 'active',
    tags: ['shooter', 'classic', 'hand-drawn', 'microsoft', 'xbox'],
    images: ['https://picsum.photos/400/600?random=18'],
    image: 'https://picsum.photos/400/600?random=18',
    is_digital: true,
    compatibility: 'Xbox One, Xbox Series X/S, PC'
  },
  {
    title: 'لعبة Grounded',
    title_en: 'Grounded',
    description: 'مغامرة البقاء في حديقة خلفية عملاقة مليئة بالحشرات',
    description_en: 'Survival adventure in a giant backyard full of insects',
    price: 189,
    category: 'xbox',
    subcategory: 'Xbox Series X',
    sku: 'MT0018',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['survival', 'adventure', 'multiplayer', 'microsoft', 'xbox'],
    images: ['https://picsum.photos/400/600?random=19'],
    image: 'https://picsum.photos/400/600?random=19',
    is_digital: true,
    compatibility: 'Xbox One, Xbox Series X/S, PC'
  },
  {
    title: 'لعبة Psychonauts 2',
    title_en: 'Psychonauts 2',
    description: 'مغامرة نفسية في عقول الآخرين مع راي وفريقه',
    description_en: 'Psychological adventure in other people\'s minds with Raz and his team',
    price: 199,
    category: 'xbox',
    subcategory: 'Xbox Series X',
    sku: 'MT0019',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['adventure', 'platform', 'psychology', 'microsoft', 'xbox'],
    images: ['https://picsum.photos/400/600?random=20'],
    image: 'https://picsum.photos/400/600?random=20',
    is_digital: true,
    compatibility: 'Xbox One, Xbox Series X/S, PC'
  },
  {
    title: 'لعبة Tell Me Why',
    title_en: 'Tell Me Why',
    description: 'قصة تفاعلية مؤثرة عن الاختيار والحرية الشخصية',
    description_en: 'Touching interactive story about choice and personal freedom',
    price: 129,
    category: 'xbox',
    subcategory: 'Game Pass',
    sku: 'MT0020',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['story', 'interactive', 'emotional', 'microsoft', 'xbox'],
    images: ['https://picsum.photos/400/600?random=21'],
    image: 'https://picsum.photos/400/600?random=21',
    is_digital: true,
    compatibility: 'Xbox One, Xbox Series X/S, PC'
  },

  // Continue with more categories...
  // For brevity, I'll add a few more key products and then provide the insertion logic
  {
    title: 'لعبة The Legend of Zelda: Tears of the Kingdom',
    title_en: 'The Legend of Zelda: Tears of the Kingdom',
    description: 'مغامرة زيلدا الجديدة في عالم هيروول الشاسع مع قدرات جديدة',
    description_en: 'New Zelda adventure in the vast world of Hyrule with new abilities',
    price: 349,
    category: 'nintendo',
    subcategory: 'Switch',
    sku: 'MT0021',
    stock: 999,
    is_new: true,
    is_limited: true,
    status: 'active',
    tags: ['adventure', 'open-world', 'nintendo', 'switch', 'zelda'],
    images: ['https://picsum.photos/400/600?random=22'],
    image: 'https://picsum.photos/400/600?random=22',
    is_digital: true,
    compatibility: 'Nintendo Switch'
  },
  {
    title: 'لعبة Super Mario Odyssey',
    title_en: 'Super Mario Odyssey',
    description: 'مغامرة ماريو حول العالم في رحلة لإنقاذ الأميرة بيتش',
    description_en: 'Mario adventure around the world on a journey to save Princess Peach',
    price: 299,
    category: 'nintendo',
    subcategory: 'Switch',
    sku: 'MT0022',
    stock: 999,
    is_new: false,
    is_limited: false,
    status: 'active',
    tags: ['platform', 'adventure', 'mario', 'nintendo', 'switch'],
    images: ['https://picsum.photos/400/600?random=23'],
    image: 'https://picsum.photos/400/600?random=23',
    is_digital: true,
    compatibility: 'Nintendo Switch'
  }
];

// Generate more products for remaining categories
const categories = ['pc', 'mobile', 'accessories', 'guide', 'physical', 'consultation', 'tshirts'];
let productIndex = 23;

categories.forEach((category, categoryIdx) => {
  for (let i = 0; i < 8; i++) { // 8 more products per category to reach 10 total
    const product = {
      title: `منتج ${category} ${i + 1}`,
      title_en: `${category.toUpperCase()} Product ${i + 1}`,
      description: `وصف منتج ${category} باللغة العربية`,
      description_en: `Description of ${category} product in English`,
      price: 50 + Math.random() * 200,
      category,
      subcategory: 'General',
      sku: `MT${String(productIndex + 1).padStart(4, '0')}`,
      stock: ['guide', 'consultation', 'pc', 'mobile'].includes(category) ? 999 : Math.floor(Math.random() * 500) + 1,
      is_new: Math.random() > 0.7,
      is_limited: Math.random() > 0.8,
      status: 'active',
      tags: ['gaming', category, 'quality'],
      images: [`https://picsum.photos/400/600?random=${productIndex + 1}`],
      image: `https://picsum.photos/400/600?random=${productIndex + 1}`,
      is_digital: !['physical', 'tshirts', 'accessories'].includes(category),
      compatibility: category === 'pc' ? 'Windows 10/11' : 'All platforms'
    };
    sampleProducts.push(product);
    productIndex++;
  }
});

console.log(`Generated ${sampleProducts.length} sample products`);
console.log('Sample products ready for insertion into Supabase');