// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kifkhuesoiconjckvwdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZmtodWVzb2ljb25qY2t2d2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDE4OTMsImV4cCI6MjA3MjY3Nzg5M30.R1lKpo0Sz3zPuPJwtEy0JBlKyCJ8rDovZ7Gx8V9cd9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});